#ifndef NRFX_CONFIG_H__
#define NRFX_CONFIG_H__


#define NRFX_SYSTICK_ENABLED            1

#define NRFX_CLOCK_ENABLED              1
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY  6
#define NRFX_CLOCK_CONFIG_LF_SRC        0

#define NRFX_CLOCK_DEFAULT_CONFIG_IRQ_PRIORITY 6


#endif // NRFX_CONFIG_H__
